### ISSUE TITLE
This is not working

### ISSUE THREAD

**Issue by anthonyyoussef01** [rdwz/get-vercel-source-code#11]
```
backup
✖ Getting deployment id 🏷️
HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (file:///C:/Users/antho/WebstormProjects/vercel-source-fetcher/node_modules/got/dist/source/as-promise/index.js:86:42)
    at Object.onceWrapper (node:events:634:26)
    at Request.emit (node:events:531:35)
    at Request._onResponseBase (file:///C:/Users/antho/WebstormProjects/vercel-source-fetcher/node_modules/got/dist/source/core/index.js:603:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Request._onResponse (file:///C:/Users/antho/WebstormProjects/vercel-source-fetcher/node_modules/got/dist/source/core/index.js:645:13)
```

**Comment by rdwz** [comment]
🛠 Finally, a new, refreshed and working version
of the Vercel Source Code Down Loader ([VSCDL](https://npm.im/vscdl)) 🎁
